/** User-facing strings. Every line follows docs/design/04-copy-tone-guide.md. */
import type { EnergyLevel } from '../domain/model';

export const copy = {
  appName: 'Become Who You Are',
  energyQuestion: 'How much force have you got right now?',
  energyLabels: { high: 'plenty', medium: 'some', low: 'not much', fried: 'fried' } as Record<EnergyLevel, string>,
  friedNote: 'Then today is autopilot day. Only the light things are showing.',

  nowHeader: 'Next',
  didIt: 'I did it',
  tooBig: 'still too big',
  notNow: 'not now',
  anotherStep: 'another step',
  editStep: 'in my words',
  save: 'save',
  cancel: 'cancel',

  started: 'Started.',
  keepGoing: 'Keep going',
  thatCounts: 'That counts. Stop here.',
  pickUp: 'Pick up where you left off.',
  done: 'Done',
  doneFlash: 'Done.',
  completions: ['Imposed on the world.', 'That exists now because of you.', 'One less weight.'],

  slipTitle: 'This one keeps slipping.',
  slipBody: "That usually means it's built wrong, not that you are. Shrink it, or let it go?",
  reshapeTitle: 'This might need a different shape.',
  reshapeBody: "Smaller didn't help, so size isn't the problem. Put the first step in your own words, or let it go?",
  shrink: 'shrink it',
  letGo: 'let it go',
  itsFine: "it's fine",
  released: 'Released. Looking away is allowed.',

  capturePlaceholder: "Dump it here. Don't sort it.",
  captured: 'Captured. First step ready.',
  alsoHere: 'Also here',
  heldBack: (n: number) => `${n} heavier ${n === 1 ? 'thing is' : 'things are'} resting until you have more force.`,

  feeds: (statement: string) => `feeds ${statement}`,
  becomingLink: 'Becoming',
  nowLink: 'Now',

  onboarding: {
    camelTitle: "Dump everything you're carrying.",
    camelBody: "Talk or type. One thing per line. Don't sort it.",
    camelPlaceholder: 'email the landlord\ntaxes\ncall mom\nthat thing about the car',
    lionTitle: 'Most of that was handed to you.',
    lionBody: 'Which of it do you actually want?',
    keep: 'keep',
    notMine: 'not mine',
    notNowShort: 'not now',
    childTitle: 'Who are you becoming?',
    childBody: 'Not a goal. A person.',
    childExamples: ['someone who writes every week', "a dad who's actually in the room", 'someone whose home feels like a home'],
    childSkip: "I don't know yet",
    childSkipNote: "You don't have to know yet.",
    amorTitle: 'Your brain works differently.',
    amorBody:
      'It has real costs, and real powers: hyperfocus, speed under pressure, novelty-hunting, sideways ideas. This app is built for the brain you have.',
    optInTitle: 'One more thing.',
    optInBody:
      'Want an occasional question about whether things deserve their place in your life? You can turn it off anytime.',
    optInYes: 'Yes',
    optInNo: 'Not now',
    next: 'Continue',
    skip: 'skip',
  },

  recurrence: {
    question: 'If you had to live this day again, innumerable times, exactly the same, would you keep this on the list?',
    yes: 'Yes, again',
    no: 'No',
    unsure: 'not sure',
    skip: 'skip',
    close: 'close',
    noTitle: "Then let's question it.",
    reshape: 'Reshape it',
    rarer: 'Make it rarer',
    toll: "It's a toll",
    letGo: 'Let it go',
    keep: 'Keep it anyway',
    betterDay: 'Ask me again on a better day',
    reshapeTitle: "What would a version you'd say yes to look like?",
    tollTitle: "This one's a toll, not a choice.",
    tollBody: 'Some things are the price of a life you want. Could this one weigh less?',
    lowerBar: 'Lower the bar',
    tollFine: "It's fine as is",
    unsureTitle: 'Fair.',
    unsureBody: 'Want to look at it closer, or ask me again next week?',
    lookCloser: 'Look closer',
    nextWeek: 'Next week',
    keptNote: 'Your call. It stays.',
    rarerNote: 'Looser now. See how it feels.',
    tollNote: "Marked as a toll. You won't be asked if it should exist.",
    linkTitle: 'Who does this make you?',
    mostlyNo: "That's a lot of no. That's important information, not a crisis. Look at the bigger picture in Becoming sometime.",
    frequencyTitle: "You've skipped this a few times.",
    frequencyBody: 'Ask less often, or not at all?',
    less: 'Less often',
    off: 'Not at all',
    same: 'Keep asking',
  },

  becoming: {
    title: 'Who are you becoming?',
    empty: "You don't have to know yet.",
    addPlaceholder: 'someone who…',
    add: 'add',
    outgrow: 'outgrown',
    authored: (a: number, t: number) => `${a} of ${t} routines are ones you'd live again.`,
    authoredTitle: 'Your list, authored.',
    routines: 'Routines',
    routinePlaceholder: 'a walk, morning pages, call mom…',
    cadence: { daily: 'daily', few_per_week: 'few times a week', weekly: 'weekly', monthly: 'monthly' } as Record<string, string>,
    standing: {
      affirmed: "you'd live it again",
      questioned: 'questioned',
      reshaping: 'reshaping',
      unasked: 'not asked yet',
    } as Record<string, string>,
    tollLabel: 'a toll',
    released: 'Released',
    releasedEmpty: 'Nothing released yet. Letting go is a skill too.',
    releasedNote: "What you let go made room. It's restorable here.",
    recurrenceSetting: 'Ask the recurrence question sometimes',
    aphorism: { text: 'You shall become the person you are.', source: 'The Gay Science §270' },
  },

  emptyNow: "Nothing here. Either you're done, or you're about to capture something. Both are good.",
  aphorism: {
    text: 'One must still have chaos in oneself to be able to give birth to a dancing star.',
    source: 'Thus Spoke Zarathustra, Prologue §5',
  },
};

export function completionLine(seed: number): string {
  return copy.completions[Math.abs(seed) % copy.completions.length];
}
